[package]
name = "rust_lib_frb_large_transfer_hang_reproduction"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gloo-console = "0.3.0"
flutter_rust_bridge = "=2.4.0"
web-time = "1.1"
